---
- name: "create web dir"
  file: 
    path: "~/web"
    state: directory

- name: "copy index"
  copy:
    src: "index.js"
    dest: "~/web/index.js"
  
- name: "start the server"
  shell: "pm2 start ~/web/index.js -f"